# Site settings
name: Mobile-optimized Websites for the Firefox Marketplace
title: Mobile-optimized Websites for the Firefox Marketplace
author: Mozilla Firefox Marketplace UX team
email: marketplace-ux@mozilla.com
description: "User experience design for integrating mobile-optimized websites into Marketplace"
#below url of GHPages account where project is hosted
url: "http://marketplaceux.github.io"
#below github project name WITHOUT the trailing /
baseurl: "/mow" 
#below url to this project's Open Issues on github
openissuesurl: "https://github.com/MarketplaceUX/mow/issues"
#below url to this project's Master Branch on github
masterbranchurl: "https://github.com/MarketplaceUX/mow/"



# Build settings
markdown: redcarpet
highlighter: pygments

# List of the main sections - not used anywhere - for ref only
Section1: '/'
Section2: '/project'
Section3: '/background'
Section4: '/strategy'
Section5: '/concepts'
Section6: '/design'


# NOTES ON THE LIST BELOW
# Add more pages as you create them
# Re-number following pages in sequence if you add a page in the middle
# You can group them with a line break as long cursor is to far left on the line break line
# First = url
# Second = the group name of the page (make sure you've added that to the page's front matter)
# Third = the page's subnav title

# List of Pages 
# Within each group, pages listed IN SUBNAV DISPLAY ORDER
section_list:
  0: ['/', 'section1', 'Home']

  1: ['/project/index.html', 'section2', 'Overview']
  2: ['/project/goals.html', 'section2', 'Goals + Metrics']

  3: ['/background/index.html', 'section3', 'Overview']
  4: ['/background/research.html', 'section3', 'Research']

  5: ['/strategy/index.html', 'section4', 'Overview']
  6: ['/strategy/reqs.html', 'section4', 'Requirements']
  7: ['/strategy/designstrats.html', 'section4', 'Design Strategies']

  8: ['/concepts/index.html', 'section5', 'Overview']

  9: ['/design/index.html', 'section6', 'Overview']




